### PR TITLE
ap-nimbus-app-manager Release 2.0.0

### LINKED ISSUE #75: Release Ap-Nimbus v2.0.0
### [appredict-docker](https://github.com/CardiacModelling/appredict-docker)

- [x] Update to [Chaste 2024.1](https://github.com/Chaste/Chaste/releases/tag/2024.1) and [ApPredict 2024.1](https://github.com/Chaste/ApPredict/releases/tag/v2024.1)
- [x] Upgrade base image to debian bullseye.
- [x] Build [appredict-chaste-libs](https://hub.docker.com/r/cardiacmodelling/appredict-chaste-libs):2.0.0 docker image.
- [x] Build [appredict-no-emulators](https://hub.docker.com/r/cardiacmodelling/appredict-no-emulators):2.0.0 docker image.
- [x] Build [appredict-with-emulators](https://hub.docker.com/r/cardiacmodelling/appredict-with-emulators):2.0.0 docker image.
- [x] Release repository v2.0.0

### [ap-nimbus-app-manager](https://github.com/CardiacModelling/ap-nimbus-app-manager)
- [x] Update to appredict-with-emulators:2.0.0 base image.
- [x] Upgrade to [Node 20](https://nodejs.org/en/blog/release/v20.15.0).
- [x] Build [ap-nimbus-app-manager](https://hub.docker.com/r/cardiacmodelling/ap-nimbus-app-manager):2.0.0 docker image.
- [x] Release repository v2.0.0

### [ap-nimbus-client](https://github.com/CardiacModelling/ap-nimbus-client)
- [x] Support Python 3.12
- [x] Build [ap-nimbus-client](https://hub.docker.com/r/cardiacmodelling/ap-nimbus-client/):2.0.0 docker image.
- [x] User Acceptance Testing
- [x] Release repository v2.0.0

### [ap-nimbus](https://github.com/CardiacModelling/ap-nimbus)
- [x] Update RtD documentation.
- [x] Update submodules for appredict-docker, app-manager, and ap-nimbus client to v2.0.0.
- [ ] Release repository v2.0.0

### PR DESCRIPTION
**Pull request by kwabenantim**
* Supports https://github.com/CardiacModelling/ap-nimbus/issues/75

### CODE REVIEW

**Comment by kwabenantim** [comment]
The current "Active LTS" is now [Node 20](https://nodejs.org/en/blog/release/v20.9.0), and [Node 18](https://nodejs.org/en/blog/release/v18.12.0) is currently in "Maintenance" mode. It is probably a good time to upgrade.

**Comment by kwabenantim** [comment]
The [ip package](https://github.com/indutny/node-ip) no longer seems to be in active maintenance.

```
# npm audit report

ip  *
Severity: high
ip SSRF improper categorization in isPublic - https://github.com/advisories/GHSA-2p57-rm9w-gvfp
No fix available
node_modules/ip

1 high severity vulnerability

Some issues need review, and may require choosing
a different dependency.
```

**Comment by kwabenantim** [comment]
The ip github repository has recently been unarchived again. However, the dependabot alert remains.

Currently, app-manager only needs ip to [retrieve an address](https://github.com/CardiacModelling/ap-nimbus-app-manager/blob/ac588b25eb70a437d6f2736357353c8b4aa0da1b/server.js#L949):

```javascript
const ip = require('ip');
return_obj = {'success': {'id': simulation_id,'ip': ip.address()}};
```

This could manually be replaced with a manual function similar to:

```javascript
const os = require('os');

function ip_address() {
  const interfaces = os.networkInterfaces();

  for (const networks of Object.values(interfaces)) {
    for (const network of networks) {
      if (network.family == 'IPv4' && !network.internal) {
        return network.address;
      }
    }
  }

  return "127.0.0.1";
}

return_obj = {'success': {'id': simulation_id,'ip': ip_address()}};
```

**Comment by mirams** [comment]
All OK by me

**Pull request merged**
